fix addCustomHeader error
ERROR: Object->__call(): the method 'addCustomHeader' does not exist on 'SilverStripe\Newsletter\Control\Email\NewsletterEmail'
{"exception":"[object] (BadMethodCallException(code: 0): Object->__call(): the method 'addCustomHeader' does not exist
on 'SilverStripe\\Newsletter\\Control\\Email\\NewsletterEmail'

Method addCustomHeader is not part of the NewsletterEmail class or its parents, called in src/Model/SendRecipientQueue.php line 82
    $email->addCustomHeader('Reply-To', $newsletter->ReplyTo);
Because it's the only occurrence and is used for setting the Reply-To header, we can use
    $email->setReplyTo($newsletter->ReplyTo);
instead.